groups:
  - name: alert_rules
    interval: 1s
    rules:
      - alert: container_not_running
        expr: |
          time() - container_last_seen{name="dice-api"} > 10
            or
          time() - container_last_seen{name="dice-api-grafana"} > 10
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: Container "{{ $labels.name }}" not running
          description: 'container "{{ $labels.name }}" down for more than {{ $value | printf "%.0f" }} seconds'
      - alert: lot_of_dice-api_flips
        expr: rate(flip_count{job="dice-api"}[1m]) * 60 > 1000
        for: 1s
        labels:
          severity: critical
        annotations:
          summary: The dice-api flip server is experiencing a lot of dice-api flips.
          description: 'An estimated {{ $value | printf "%.0f" }} dice-apis have been flipped in the last minute.'
      - alert: low_usage_of_dice_flips
        expr: rate(roll_count{job="dice-api"}[1m]) = 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: The dice-api flip server is experiencing a low usage of dice flip.
          description: "An estimated 0 dice-apis have been flipped in the last minute."
